INSERT INTO MARCA(DESCRICAO) VALUES('FORD');
INSERT INTO MARCA(DESCRICAO) VALUES('FIAT');
INSERT INTO MARCA(DESCRICAO) VALUES('VOLKS');
INSERT INTO MARCA(DESCRICAO) VALUES('GM');

INSERT INTO USUARIO(EMAIL, SENHA) VALUES('iza@email', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');
INSERT INTO USUARIO(EMAIL, SENHA) VALUES('gisele@email', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');
INSERT INTO USUARIO(EMAIL, SENHA) VALUES('luana@email', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');
INSERT INTO USUARIO(EMAIL, SENHA) VALUES('juliana@email', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');

INSERT INTO PERFIL(id, nome) VALUES(3, 'ROLE_ALUNO');
INSERT INTO PERFIL(id, nome) VALUES(4, 'ROLE_MODERADOR');

INSERT INTO USUARIO_PERFIS(usuario_id, perfis_id) VALUES(1, 1);
INSERT INTO USUARIO_PERFIS(usuario_id, perfis_id) VALUES(2, 2);